name: Create Release Note
on:
  release:
    types: [published]
jobs:
  create-release-note:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create release note
        run: |
          echo "# ${{ github.event.release.name }}" > docs/${{ github.event.release.tag_name }}.md
          echo "${{ github.event.release.body }}" >> docs/${{ github.event.release.tag_name }}.md
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Release ${{ github.event.release.tag_name }}"
          add: "docs/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
